os: linux
language: rust
cache:
  cargo: true
  ccache: true
  apt: true
  directories:
    $HOME/Nyx-Testing/.git/modules
dist: focal

addons:
  apt:
    packages:
      - ccache
      - libgtk-3-dev
      - libc6-dev-i386
      - gcc-multilib

before_install:
- sudo modprobe -r kvm-intel
- sudo modprobe -r kvm
- sudo modprobe  kvm enable_vmware_backdoor=y
- sudo modprobe  kvm-intel
- cat /sys/module/kvm/parameters/enable_vmware_backdoor
- export MAKEFLAGS="-j$(expr $(nproc) \+ 1)" && echo $MAKEFLAGS
- sudo chmod +666 /dev/kvm # this is unsafe in your local machine!
# - export CC="ccache clang" && export CXX="ccache clang++"

install:
  - sh setup.sh
  - sh prepare_tests.sh

script: ./run_tests.sh
script: ./run_tests_pt.sh
